In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
songs = pd.read_csv("Data\data.csv")

In [4]:
songs.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [5]:
song_info = songs[["name","artists"]]

In [6]:
X = songs.drop(["id","name","artists","release_date"], axis=1)

In [8]:
X

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
0,0.0594,1921,0.98200,0.279,831667,0.211,0,0.878000,10,0.6650,-20.096,1,4,0.0366,80.954
1,0.9630,1921,0.73200,0.819,180533,0.341,0,0.000000,7,0.1600,-12.441,1,5,0.4150,60.936
2,0.0394,1921,0.96100,0.328,500062,0.166,0,0.913000,3,0.1010,-14.850,1,5,0.0339,110.339
3,0.1650,1921,0.96700,0.275,210000,0.309,0,0.000028,5,0.3810,-9.316,1,3,0.0354,100.109
4,0.2530,1921,0.95700,0.418,166693,0.193,0,0.000002,3,0.2290,-10.096,1,2,0.0380,101.665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170648,0.6080,2020,0.08460,0.786,301714,0.808,0,0.000289,7,0.0822,-3.702,1,72,0.0881,105.029
170649,0.7340,2020,0.20600,0.717,150654,0.753,0,0.000000,7,0.1010,-6.020,1,68,0.0605,137.936
170650,0.6370,2020,0.10100,0.634,211280,0.858,0,0.000009,4,0.2580,-2.226,0,76,0.0809,91.688
170651,0.1950,2020,0.00998,0.671,337147,0.623,1,0.000008,2,0.6430,-7.161,1,70,0.3080,75.055
170652,0.6420,2020,0.13200,0.856,189507,0.721,1,0.004710,7,0.1820,-4.928,1,74,0.1080,94.991

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [10]:
scaler = StandardScaler()

In [11]:
X_scaled = scaler.fit_transform(X)

In [18]:
X["popularity"] = X["popularity"] * 2
X["danceability"] = X["danceability"] * 1.5

In [19]:
knn = NearestNeighbors(n_neighbors=10, metric="cosine")
knn.fit(X_scaled)

NearestNeighbors(metric='cosine', n_neighbors=10)

In [20]:
def recommend(song_index):
    distances, indices = knn.kneighbors([X_scaled[song_index]])
    return songs.iloc[indices[0]][["name","artists","popularity"]]

In [21]:
recommend(100)

,name,artists,popularity
100,Dolorosa,['Robert Jysor'],0
404,Ma Chanson,"['Eugénie Buffet', 'René De Buxeuil']",0
482,L'âme des roses,['René De Buxeuil'],0
794,Mon Bus'ness,['Mistinguett'],0
63,Si J'avais Su,['Alice Cocéa'],0
26,Je M'donne,['Maurice Chevalier'],0
140889,C'est Mon Gigolo,['Damia'],0
583,Ca n'est pas la même chose,['Maurice Chevalier'],0
21633,Ici L'on Pêche,['Jean Tranchant'],0
326,C'est Au Bal Musette,['Gaby Montbreuse'],0

In [22]:
def recommend_song(song_name):
    idx = songs[songs["name"] == song_name].index[0]
    distances, indices = knn.kneighbors([X_scaled[idx]])
    return songs.iloc[indices[0]][["name","artists"]]

In [23]:
recommend_song("Blinding Lights")

                            name              artists
19616            Blinding Lights       ['The Weeknd']
17428                    Secrets      ['OneRepublic']
18039   They Don't Know About Us    ['One Direction']
19037                    Thunder  ['Imagine Dragons']
19627          Forever After All       ['Luke Combs']
17410                  Fireflies         ['Owl City']
37960                Getaway Car     ['Taylor Swift']
57363            Black And White      ['Niall Horan']
108337                Magic Shop              ['BTS']
18970       Versace on the Floor       ['Bruno Mars']

### Output

1. Implemented a **KNN-based similarity model** to identify songs with similar audio features.

2. Built a **function to recommend similar songs** based on a given input song.

3. Demonstrated a **content-based music recommendation system** that suggests songs using feature similarity.